on: [push]

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: Send test message

    steps:
      - name: message
        uses: juztcode/gitter-github-action@v2
        with:
          room-id: ${{ secrets.GITTER_ROOM_ID }}
          token: ${{ secrets.GITTER_TOKEN }}
          text: Success
    #  uses: juztcode/gitter-github-action@v1
    #  with:
    #    room-id: ${{ secrets.GITTER_ROOM_ID }}
    #    token: ${{ secrets.GITTER_TOKEN }}
    #    text: Pending


        #message-id: ${{ steps.initial.outputs.message-id }}
